// <auto-generated />
using System;
using Komi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Komi.Data.Migrations
{
    [DbContext(typeof(KomiContext))]
    [Migration("20200625134604_RemoveCollaborators")]
    partial class RemoveCollaborators
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Komi.Data.Models.Groups.Group", b =>
                {
                    b.Property<decimal>("GuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GuildId");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Komi.Data.Models.Moderation.Warning", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Count")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("GroupGuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("ModId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GroupGuildId");

                    b.HasIndex("ModId");

                    b.HasIndex("UserId");

                    b.ToTable("Warning");
                });

            modelBuilder.Entity("Komi.Data.Models.Settings.GroupSetting", b =>
                {
                    b.Property<decimal>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(20,0)");

                    b.Property<int?>("BanAt")
                        .HasColumnType("integer");

                    b.Property<int?>("KickAt")
                        .HasColumnType("integer");

                    b.Property<decimal>("TrackingChannel")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("GroupId");

                    b.ToTable("GroupSetting");
                });

            modelBuilder.Entity("Komi.Data.Models.Settings.Prefix", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("GroupSettingGroupId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GroupSettingGroupId");

                    b.ToTable("Prefix");
                });

            modelBuilder.Entity("Komi.Data.Models.Settings.WorkTypeSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("GroupSettingGroupId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<int>("WorkType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupSettingGroupId");

                    b.ToTable("WorkTypeSetting");
                });

            modelBuilder.Entity("Komi.Data.Models.Tracking.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WorkId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkId");

                    b.ToTable("Job");
                });

            modelBuilder.Entity("Komi.Data.Models.Tracking.Scanlation.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("GroupGuildId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GroupGuildId");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("Komi.Data.Models.Tracking.Scanlation.Work", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Chapter")
                        .HasColumnType("double precision");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("GroupGuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int?>("OverridenStatus")
                        .HasColumnType("integer");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid");

                    b.Property<double?>("Volume")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("GroupGuildId");

                    b.HasIndex("SeriesId");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("Komi.Data.Models.Tracking.Worker", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<DateTimeOffset>("Finished")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("Started")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("Worker");
                });

            modelBuilder.Entity("Komi.Data.Models.Users.GroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("GroupGuildId")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("UserId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("Id");

                    b.HasIndex("GroupGuildId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("Komi.Data.Models.Users.User", b =>
                {
                    b.Property<decimal>("Id")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Komi.Data.Models.Moderation.Warning", b =>
                {
                    b.HasOne("Komi.Data.Models.Groups.Group", null)
                        .WithMany("Warnings")
                        .HasForeignKey("GroupGuildId");

                    b.HasOne("Komi.Data.Models.Users.User", "Mod")
                        .WithMany()
                        .HasForeignKey("ModId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Komi.Data.Models.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Komi.Data.Models.Settings.GroupSetting", b =>
                {
                    b.HasOne("Komi.Data.Models.Groups.Group", null)
                        .WithOne("GroupSettings")
                        .HasForeignKey("Komi.Data.Models.Settings.GroupSetting", "GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Komi.Data.Models.Settings.Prefix", b =>
                {
                    b.HasOne("Komi.Data.Models.Settings.GroupSetting", null)
                        .WithMany("Prefixes")
                        .HasForeignKey("GroupSettingGroupId");
                });

            modelBuilder.Entity("Komi.Data.Models.Settings.WorkTypeSetting", b =>
                {
                    b.HasOne("Komi.Data.Models.Settings.GroupSetting", null)
                        .WithMany("DefaultWorkTypes")
                        .HasForeignKey("GroupSettingGroupId");
                });

            modelBuilder.Entity("Komi.Data.Models.Tracking.Job", b =>
                {
                    b.HasOne("Komi.Data.Models.Tracking.Scanlation.Work", null)
                        .WithMany("Jobs")
                        .HasForeignKey("WorkId");
                });

            modelBuilder.Entity("Komi.Data.Models.Tracking.Scanlation.Series", b =>
                {
                    b.HasOne("Komi.Data.Models.Groups.Group", null)
                        .WithMany("Projects")
                        .HasForeignKey("GroupGuildId");
                });

            modelBuilder.Entity("Komi.Data.Models.Tracking.Scanlation.Work", b =>
                {
                    b.HasOne("Komi.Data.Models.Groups.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupGuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Komi.Data.Models.Tracking.Scanlation.Series", null)
                        .WithMany("Works")
                        .HasForeignKey("SeriesId");
                });

            modelBuilder.Entity("Komi.Data.Models.Tracking.Worker", b =>
                {
                    b.HasOne("Komi.Data.Models.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Komi.Data.Models.Tracking.Job", "Job")
                        .WithMany("Workers")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Komi.Data.Models.Users.GroupMember", b =>
                {
                    b.HasOne("Komi.Data.Models.Groups.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupGuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Komi.Data.Models.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
